### ISSUE TITLE
proc-macro-error is unmaintained

### ISSUE THREAD

**Issue by jayvdb** [boringcactus/proc-macro2-error#1]
c.f. https://github.com/rustsec/advisory-db/pull/2057

Perhaps your approach here is worth being an alternative?  Is it ready to be published?

note https://crates.io/crates/proc-macro-error2 already exists, so that name cant be used.

**Comment by GnomedDev** [comment]
This fork doesn't update syn to version 2, which was the main reason I PR'd the unmaintained advisory and made my proc-macro-error2.

**Comment by boringcactus** [comment]
I also only made this fork for https://github.com/boringcactus/proc-macro-expandinator, which I haven't cared about in years. I'm not likely to start maintaining this fork, so I'm disinclined to publish it.
